[package]
name = "chip8dk"
version = "0.1.0"
authors = ["Guillermo Rodriguez <guillermor@fing.edu.uy>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"
byteorder = "1.3"
sdl2 = "0.34"